### ISSUE TITLE
DataFetchingException for bitmoji

### ISSUE THREAD

**Issue by jdleo** [Snap-Kit/bitmoji-sample#1]
It's pulling displayName from user data, but bitmoji URL is coming back as nil under every circumstance (user is authenticated at this point). I've tried with LoginKit and also BitmojiKit. It's getting the same "DataFetchingException" when trying to fetch the avatar URL from snap's server. Something seems to be broken on Snap's end.

**Comment by manwithsteelnerves** [comment]
Yes. Still its the same case.

**Comment by davidxiasc** [comment]
@jdleo It's possible that we had some transient errors in our service - does this still happen very often for you?

**Comment by yanggaosc2** [comment]
@jdleo any chance you could also verify your app has "Bitmoji avatar" permission on in https://kit.snapchat.com/portal/?

**Comment by manwithsteelnerves** [comment]
@yanggaosc2  @davidxiasc  Yes, this happens every time. Bitmoji Avatar was set on in portal.

Can you please let me know what else could be the issue?

**Comment by davidxiasc** [comment]
Hi @manwithsteelnerves, can you email your application's client id to snapkit-support@snap.com? We'll try to help diagnose the issue as soon as possible!

**Comment by manwithsteelnerves** [comment]
@davidxiasc Thanks a lot David :)
In fact, I lost the hope as I was not getting any responses and no official support email. Now I will do it right away. 

Once again, thanks for the quick response.

Cheers,
Ayyappa

**Comment by bbookman** [comment]
If anyone on this thread would like ..  I've started a [repo ](https://github.com/bbookman/Snapchat-Snapkit-DIY-Docs/tree/develop)for collecting documentation and best practices for SnapKit

**Comment by Deloww** [comment]
[](https://github.com/Snapchat/bitmoji-kit-sample/issues/22) https://github.com/Snap-Kit/bitmoji-sample/issues/1
