### ISSUE TITLE
com.snapchat.kit.sdk.core.security.Fingerprint.<init> + 16 (SourceFile:16)

### ISSUE THREAD

**Issue by safety97** [Snap-Kit/bitmoji-sample#17]
Hello snapchat team,

I got this error everytime i run my app with the SDK on an emulator : 

`Fatal Exception: java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/fr.protox.dieselist-z4LGc-IaGKownMGvjfrgAQ==/base.apk"],nativeLibraryDirectories=[/data/app/fr.protox.dieselist-z4LGc-IaGKownMGvjfrgAQ==/lib/x86, /data/app/fr.protox.dieselist-z4LGc-IaGKownMGvjfrgAQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libpruneau.so"`

No problems when I run on a real device, but it's painful to make test. 

 `//Snapchat
  implementation([
  'com.snapchat.kit.sdk:login:1.2.0',
  'com.snapchat.kit.sdk:core:1.2.0',
  ])
  implementation('com.snapchat.kit.sdk:bitmoji-search:1.2.0')
  implementation('com.snapchat.kit.sdk:bitmoji:1.2.0')`

Any idea ?![bitmoji](https://render.bitstrips.com/v2/cpanel/33dd5e8f-cc39-4cc1-af24-e49c70b17dc9-823f76d5-8bdc-41e8-9a59-79400037f91f-v1.png?transparent=1&palette=1&width=246)

**Comment by maxschmeling** [comment]
I have this same issue and just wasted another couple hours trying to figure it out again because I forgot about this simulator issue. I'm not a native Android expert so I'm not sure if there's a good path forward, but this seems like it could pop up for a lot of people.

**Comment by sudcha90** [comment]
Getting same error on emulator on Android (APK 27).

"couldn't find "libpruneau.so".

Snapchat team -- Any updates here?

**Comment by sudcha90** [comment]
Quick google search suggests that ht compiler is trying to build the application in 64bit instead of 32 bit. 
https://github.com/deeplearning4j/nd4j/issues/2217
https://stackoverflow.com/questions/29298522/java-lang-unsatisfiedlinkerror-when-loading-native-library-in-android-5-0/29329413#29329413

**Comment by maxschmeling** [comment]
I was never able to get it working in the Android simulator. It works on a physical device though.

**Comment by Cyral** [comment]
+1 Also running into this issue

**Comment by davidxiasc** [comment]
Hi all! Sorry for the late response - this repo is no longer being updated as the main reference repo should be https://github.com/Snapchat/bitmoji-kit-sample

However, for reference, you can find how to include the x86 architecture for emulator support here:

https://github.com/Snapchat/bitmoji-kit-sample/blob/master/android/bitmoji-sample-app/build.gradle#L26-L32

By adding these couple of lines to the `build.gradle` file of your app, this will enable you to specifically download the special artifact that includes the x86 version of the native library you referenced.

Hope this helps!

**Comment by MohitDholakia** [comment]
Hello

Getting this

>  Fingerprint line 16
> com.snapchat.kit.sdk.core.security.Fingerprint.<init>

in Samsung Galaxy J2 Core device

Currently using 

 'com.snapchat.kit.sdk:creative:1.6.3',
 'com.snapchat.kit.sdk:core:1.6.3'

To resolve this I have added the below lines based on the link
https://github.com/Snapchat/bitmoji-kit-sample/blob/master/android/bitmoji-sample-app/build.gradle#L26-L32
```
configurations.all {
    resolutionStrategy {
            force 'com.snapchat.kit.sdk:core:1.6.3 x86'
    }
}
```
After adding this in build.gradle file getting an error

**Failed to resolve: com.snapchat.kit.sdk:core:1.6**

This is also not working with 1.6.5 which is the latest version of the snap kit

As of now, the only solution is to downgrade it to 1.4.0 but that I don't want any possible solution for this?

**Comment by davidxiasc** [comment]
@MohitDholakia Sorry that you're experiencing this! Do you have the full stacktrace of the error you're seeing?

**Comment by davidxiasc** [comment]
Ah sorry @MohitDholakia I was referring to the full stacktrace for this issue:

> Fingerprint line 16
> com.snapchat.kit.sdk.core.security.Fingerprint.

You no longer need to include the `resolutionStrategy` section or add `x86` at the end of the version for `com.snapchat.kit.sdk:core` in `1.6` since x86 support is included in the regular artifact (`com.snapchat.kit.sdk:core:1.6.5`) as well now

**Comment by MohitDholakia** [comment]
@davidxiasc ok so is there any fix for the below crash as it is there in
 ```
'com.snapchat.kit.sdk:creative:1.6.3',
'com.snapchat.kit.sdk:core:1.6.3'
``` 
I have attached the crash log as well

Fingerprint line 16
com.snapchat.kit.sdk.core.security.Fingerprint.

![Screenshot from 2020-10-20 10-11-56](https://user-images.githubusercontent.com/17870346/96541921-a9653300-12be-11eb-93e6-570ae913607d.png)

**Comment by davidxiasc** [comment]
@MohitDholakia If you have access to a device that is experiencing the issue, could you try adding:
```
android {
    defaultConfig {
        ndkConfig.abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
    }
}
```

to your app's build.gradle to see if that helps?

**Comment by MohitDholakia** [comment]
@davidxiasc I didn't have a device but I will let you know if this issue persists after adding this

**Comment by rupinderjeet** [comment]
Hello @davidxiasc 

I am facing same issue, except that the title line is different. Other stacktace lines are similar.

```
Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: "/data/app/com.appname-YdmUBN5mOxqqlPQtPxO8sA==/lib/arm64/libpruneau.so" has bad ELF magic: 00000000
```

I use `splits { abiFilters {  } }` block in gradle to create split APKs. I have checked that ARM64 APK has the `libpruneau.so` file.

This happens at app startup. I am not able to reproduce it but the issue was reported through Crashlytics. And, the only device that is facing this issue is Xiaomi's Redmi Note 8 with Android 10.

Think you can help me here?

**Comment by davit-zakariyan** [comment]
Hi there 
I have very similar crash report but it seems it is a little bit different (permission denied)

Fatal Exception: java.lang.UnsatisfiedLinkError: 
dlopen failed: couldn't map "/mnt/asec/.../split_config.arm64_v8a.apk!/lib/arm64-v8a/libpruneau.so" segment 0: Permission denied
