### ISSUE TITLE
Error Login: Invalid redirect_uri

### ISSUE THREAD

**Issue by congdanh1608** [Snap-Kit/bitmoji-sample#20]
Hi,
I am using the Snapkit login with the development environment client key, everything works well.
But when I try to use the production environment client key, I always get the error "Something went wrong - Invalid redirect_uri".
I don't change redirect uri between development and production environment.

My App on Snapkit dashboard was approved. I also tried on the snapkit demo project also. But I get the same issue.

Here is my redirect uri: snapfriends://com.snapfriends.app/login

Androidmainifest

 
        <activity
            android:name="com.snapchat.kit.sdk.SnapKitActivity"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                
                <data
                    android:host="com.snapfriends.app"
                    android:pathPrefix="/login"
                    android:scheme="snapfriends" />
            </intent-filter>

        </activity>

        
        <meta-data
            android:name="com.snapchat.kit.sdk.clientId"
            android:value="@string/snapkit_client_id" />  (I hide this client id on here)
        <meta-data
            android:name="com.snapchat.kit.sdk.redirectUrl"
            android:value="snapfriends://com.snapfriends.app/login" />
        <meta-data
            android:name="com.snapchat.kit.sdk.scopes"
            android:resource="@array/snap_connect_scopes" />

snap_connect_scopes

> <resources>
    <string-array name="snap_connect_scopes">
        <item>https://auth.snapchat.com/oauth2/api/user.display_name</item>
        <item>https://auth.snapchat.com/oauth2/api/user.bitmoji.avatar</item>
        <item>https://auth.snapchat.com/oauth2/api/user.external_id</item>
    </string-array>
</resources>

Do you have any ideas to solve this issue? Thank you.
@davidxiasc

**Comment by davidxiasc** [comment]
Hi @congdanh1608 - I believe once your app is approved, you must also then mark the app as live through the Developer Portal in order for the production credentials to work correctly. Please verify to see if that resolves the issue

**Comment by congdanh1608** [comment]
Hi @davidxiasc 
Thanks for replay.
on Developer Portal, I couldn't find where I can mark the app as live. Could you give me screenshot or describe it?

**Comment by davidxiasc** [comment]
In the portal, it should appear in the top-right hand corner in the page for your app (sample place as where "Submit for Review" would normally be). Is the current status of your app "Approved" or "Live"?

**Comment by congdanh1608** [comment]
Hi @davidxiasc 
I get an mistake in changing some filed data, now my app's status is edited. I am not sure it is still live or not, but I just submitted and waiting again :(
I couldn't find any option to set live for my app.

**Comment by congdanh1608** [comment]
Thanks @davidxiasc 
We found a button to do it "Approved" or "Live". Thank you so much.

**Comment by appasaheb4** [comment]
i am facing login after invalid redirect_url issue still..
